### ISSUE TITLE
Api confuguration not supported

### ISSUE THREAD

**Issue by grv87** [DanySK/javadoc.io-linker#5]
`java-library` plugin changes configurations, so that `compile` is empty, but there are new configurations `api` and `implementation`.
`api` - it is what is used in public methods parameters, result types etc. So this is one that could be met in javadoc.
Please, add support for this.

**Comment by DanySK** [comment]
Hi,
thank you for your request. Would you be willing to contribute via a pull request?

**Comment by grv87** [comment]
I could, but not in the coming months.

**Comment by DanySK** [comment]
The plugin now uses `runtimeClasspath`, I'm marking this one solved.
